name: pypkg
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - pytest=9.0.2
  - python=3.14.3
  - copier=9.14.0
